padding = 20

fonts = ['Iosevka'] # list of otf or ttf fonts. later elements work as fallback
font_size = 20.0

[history]
decrease_interval = 48 # interval to decrease the number of launches in hours

[colors]
background = '#11111bbb'
prompt = '#89b4fa'
text = '#cdd6f4ff'          # for search results
text_query = '#fab387'      # for the search query
text_selected = '#61afefff' # for the currently selected result

[keybindings]
paste = ["ctrl+v"]
execute = ["KP_Enter", "Return"]
delete = ["KP_Delete", "Delete", "BackSpace"]
delete_word = ["ctrl+KP_Delete", "ctrl+Delete", "ctrl+BackSpace"]
complete = ["Tab"]
nav_up = ["Up"]
nav_down = ["Down"]
exit = ["Escape"]
