padding = 320
margin = 100

fonts = ['Iosevka'] # list of otf or ttf fonts. later elements work as fallback
font_size = 32.0

[history]
decrease_interval = 48 # interval to decrease the number of launches in hours

[colors]
background = '#282828'
prompt = '#ffffff'
text = '#dacaa1ee'          # for search results
text_query = '#fab387'      # for the search query
text_selected = '#ebdbb2ff' # for the currently selected result

[keybindings]
paste = ["ctrl+v"]
execute = ["KP_Enter", "Return"]
delete = ["KP_Delete", "Delete", "BackSpace"]
delete_word = ["ctrl+KP_Delete", "ctrl+Delete", "ctrl+BackSpace"]
complete = ["Tab"]
nav_up = ["Up"]
nav_down = ["Down"]
exit = ["Escape"]
