[package]
name = "eww-brightness"
version = "0.1.0"
edition = "2021"

[dependencies]
brightness = "0.5.0"
futures = "0.3.30"
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.117"
