[package]
name = "eww-volume"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libpulse-binding = "2.28.1"
libpulse-simple-binding = "2.28.1"
