anchor_to_edges = true
position = "top"
layer = "bottom"
height = 10
exclusive_zone = true

[[start]]
type = "clock"
format = "%l:%M %P"
format_popup = "%a,%-eth"

[[start]]
type="music"
player_type="mpd"
music_dir="/home/fisher/Music"

[start.truncate]
mode="end"
length=10

[start.icons]
play = ""
pause = ""

[[center]]
type = "focused"
show_icon = false

[center.truncate]
mode="end"
length=60

[[end]]
type = "volume"
format = "vol:{percentage}%"
max_volume = 150

[end.icons]
volume_high = "󰕾"
volume_medium = "󰖀"
volume_low = "󰕿"
muted = "󰝟"

[[end]]
type = "script"
cmd = "/home/fisher/.config/ironbar/scripts/bluetooth.sh"
mode = "poll"
interval = 5000

[[end]]
type = "clipboard"
label = "󰨸"
max_items = 3

[end.truncate]
mode = "end"
length = 64

[[end]]
type = "custom"
class = "power-menu"
tooltip = "Up: {{30000:uptime -p | cut -d ' ' -f2-}}"

[[end.bar]]
type = "button"
name = "power-btn"
label = "󰤂"
on_click = "popup:toggle"

[[end.popup]]
type = "box"
orientation = "vertical"


[[end.popup.widgets]]
type = "box"

[[end.popup.widgets.widgets]]
type = "button"
class = "power-btn"
label = "<span font-size='24pt'>󰐥</span>"
on_click = "!shutdown now"

[[end.popup.widgets.widgets]]
type = "button"
class = "power-btn"
label = "<span font-size='24pt'>󰜉</span>"
on_click = "!reboot"


