[package]
name = "eww-spotify"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "4.5.1"
mpris = "2.0.1"
reqwest = "0.11.24"
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.114"
tokio = { version = "1.36.0", features = ["full"] }
