#!/bin/sh

riverctl input pointer-1267-12721-ELAN0521:01_04F3:31B1_Touchpad natural-scroll enabled
riverctl input pointer-1267-12721-ELAN0521:01_04F3:31B1_Touchpad tap enabled
riverctl input pointer-1267-12721-ELAN0521:01_04F3:31B1_Touchpad drag enabled
riverctl input pointer-1267-12721-ELAN0521:01_04F3:31B1_Touchpad disable-while-typing enabled

riverctl map normal Super Return spawn wezterm
riverctl map normal Super B spawn 'chromium --force-dark-mode --enable-features=UseOzonePlatform --ozone-platform=wayland'

riverctl map normal Super+Shift Q exit
riverctl map normal Super Q close

riverctl map normal Super F toggle-fullscreen

for i in $(seq 1 9); do
	tags=$((1 << ($i - 1)))
	riverctl map normal Super $i set-focused-tags $tags
	riverctl map normal Super+Shift $i set-view-tags $tags
	riverctl map normal Super+Control $i toggle-focused-tags $tags
	riverctl map normal Super+Shift+Control $i toggle-view-tags $tags
done

for mode in normal locked; do
	riverctl map $mode None XF86Eject spawn 'eject -T'
	riverctl map $mode None XF86AudioRaiseVolume spawn 'pamixer --allow-boost -i 5'
	riverctl map $mode None XF86AudioLowerVolume spawn 'pamixer --allow-boost -d 5'
	riverctl map $mode None XF86AudioMute spawn 'pamixer --toggle-mute'
	riverctl map $mode None XF86AudioMedia spawn 'playerctl play-pause'
	riverctl map $mode None XF86AudioPlay spawn 'playerctl play-pause'
	riverctl map $mode None XF86AudioPrev spawn 'playerctl previous'
	riverctl map $mode None XF86AudioNext spawn 'playerctl next'
	riverctl map $mode None XF86MonBrightnessUp spawn 'light -A 0.2'
	riverctl map $mode None XF86MonBrightnessDown spawn 'light -U 0.2'
done

riverctl default-layout rivertile
rivertile -view-padding 6 -outer-padding 6 &

export MOZ_ENABLE_WAYLAND=1
export __GL_GSYNC_ALLOWED=0
export __GL_VRR_ALLOWED=0
export WLR_DRM_NO_ATOMIC=1
export QT_AUTO_SCREEN_SCALE_FACTOR=1
export QT_QPA_PLATFORM=wayland
export QT_WAYLAND_DISABLE_WINDOWDECORATION=1
export GDK_BACKEND=wayland
export XDG_CURRENT_DESKTOP=sway
export GBM_BACKEND=nvidia-drm
export __GLX_VENDOR_LIBRARY_NAME=nvidia
export WLR_NO_HARDWARE_CURSORS=1

swaybg -i /home/zinnia/dotfiles-wayland/wallpapers/everforest_dark.png -m fill &
